#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# scripts/gen-demos-compose.sh — generate docker-compose for ALL discovered
# demos. No demo is listed by hand: the service set, image names and ports all
# come from scripts/discover-demos.sh (which reads each demo's Dockerfile).
#
# Output goes to stdout. Env overrides:
#   IMAGE_OWNER   GHCR owner (default: silvanaone)
#   DEMO_TAG      image tag at deploy time (default: latest) — left as a compose
#                 variable so `deploy-demos.sh <tag>` still controls it.
#
# Per-demo image can also be overridden with <SHORT_UPPER>_IMAGE, e.g.
# SPOT_DCA_IMAGE=... for the spot-dca demo.
#
# Usage:
#   bash scripts/gen-demos-compose.sh > docker-compose.demos.yml
# ---------------------------------------------------------------------------
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
owner="${IMAGE_OWNER:-silvanaone}"

demos="$(bash "$here/discover-demos.sh")"

echo "# GENERATED by scripts/gen-demos-compose.sh — do not edit by hand."
echo "# Runs every agent demo discovered under crates/*/demo/. Add a new demo"
echo "# folder with a Dockerfile and it appears here automatically."
echo "services:"

echo "$demos" | jq -r --arg owner "$owner" '
  .[] |
  ((.short | ascii_upcase | gsub("-";"_")) + "_IMAGE") as $imgvar |
  "  \(.name):",
  "    image: ${\($imgvar):-ghcr.io/\($owner)/\(.name):${DEMO_TAG:-latest}}",
  "    build:",
  "      context: ./\(.context)",
  "    container_name: \(.name)",
  "    restart: unless-stopped",
  "    ports:",
  "      - \"\(.port):\(.port)\""
'
